model Model
	culture: en-US
	defaultPowerBIDataSourceVersion: powerBI_V3
	sourceQueryCulture: en-US
	dataAccessOptions
		legacyRedirects
		returnErrorValuesAsNull

	/// Connection to Lakehouse via OneLake
	expression Lakehouse_AI_Foundry_Control_Tower = 
		let
			database = Lakehouse.Contents(null, "{{TARGET_WORKSPACE_ID}}", "AI_Foundry_Control_Tower")
		in
			database
		lineageTag: 00000000-0000-0000-0000-000000000001

	table foundryagent_fact
		lineageTag: 00000000-0000-0000-0000-000000000002
		sourceLineageTag: [dbo].[foundryagent_fact]
		
		measure 'Total Invocations' = COUNTROWS(foundryagent_fact)
			formatString: #,##0
			lineageTag: 00000000-0000-0000-0000-000000000003
		
		measure 'Total Tokens' = SUM(foundryagent_fact[total_tokens])
			formatString: #,##0
			lineageTag: 00000000-0000-0000-0000-000000000004
		
		measure 'Avg Duration (ms)' = AVERAGE(foundryagent_fact[duration_ms])
			formatString: #,##0.00
			lineageTag: 00000000-0000-0000-0000-000000000005
		
		measure 'Success Rate %' = DIVIDE(COUNTROWS(FILTER(foundryagent_fact, foundryagent_fact[success] = TRUE())), COUNTROWS(foundryagent_fact)) * 100
			formatString: 0.00%
			lineageTag: 00000000-0000-0000-0000-000000000006
		
		column time_generated
			dataType: dateTime
			sourceColumn: time_generated
			lineageTag: 00000000-0000-0000-0000-000000000010
		
		column agent_id
			dataType: string
			sourceColumn: agent_id
			lineageTag: 00000000-0000-0000-0000-000000000011
		
		column blueprint_id
			dataType: string
			sourceColumn: blueprint_id
			lineageTag: 00000000-0000-0000-0000-000000000012
		
		column operation_name
			dataType: string
			sourceColumn: operation_name
			lineageTag: 00000000-0000-0000-0000-000000000013
		
		column request_model
			dataType: string
			sourceColumn: request_model
			lineageTag: 00000000-0000-0000-0000-000000000014
		
		column duration_ms
			dataType: double
			sourceColumn: duration_ms
			lineageTag: 00000000-0000-0000-0000-000000000015
		
		column success
			dataType: boolean
			sourceColumn: success
			lineageTag: 00000000-0000-0000-0000-000000000016
		
		column status
			dataType: string
			sourceColumn: status
			lineageTag: 00000000-0000-0000-0000-000000000017
		
		column input_tokens
			dataType: int64
			sourceColumn: input_tokens
			lineageTag: 00000000-0000-0000-0000-000000000018
		
		column output_tokens
			dataType: int64
			sourceColumn: output_tokens
			lineageTag: 00000000-0000-0000-0000-000000000019
		
		column total_tokens
			dataType: int64
			sourceColumn: total_tokens
			lineageTag: 00000000-0000-0000-0000-000000000020
		
		column date_key
			dataType: int64
			sourceColumn: date_key
			lineageTag: 00000000-0000-0000-0000-000000000021
		
		column year
			dataType: int64
			sourceColumn: year
			lineageTag: 00000000-0000-0000-0000-000000000022
		
		column month
			dataType: int64
			sourceColumn: month
			lineageTag: 00000000-0000-0000-0000-000000000023
		
		partition foundryagent_fact = m
			mode: directLake
			source
				entityName: foundryagent_fact
				schemaName: dbo
				expressionSource: Lakehouse_AI_Foundry_Control_Tower